# containers
services:
    webapp:
        build: .
        tags: 
            - webapp:1.0
        ports:
            - "8080:8080"
        networks:
            - net1
        depends_on:
            - db
        environment:
            - connectionString=${CONNECTION_STRING}
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        networks:
            - net1
        volumes:
            - dbdata:/var/opt/mssql
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=${DB_PASSWORD}
        
# networks
networks:
    net1:

# volumes
volumes:
    dbdata:
